# Site settings
title: "Personal Portfolio"
description: "A resume portfolio powered by GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shahzeb Khan"
resume_title:                   "AI Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shahzebkhan_97@outlook.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Peshawar/Islamabad"

resume_header_contact_info:     ""
display_header_contact_info:    ""

resume_header_intro: "<p>Im shahzeb, working as Ai division head at QUEM international and educator at FAST Nuces Peshawar. My expertise are in the field of Artificial Intelligence, in NLP domain where I love to experiment with NLU and NLG. From deploying chatbots locally to Creating conversational chatbot focused on local language using TTS is my day to day routine.Apart from tech, I am a firm believer of giving back to community, as I believe this is the only way to achieve greater goal</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        flase
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Shahzeb-Khn"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/wisdom-chatbot"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://Shahzeb-khn.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
